# coding: utf-8

"""
    Shared Data API

    # Overview The Shared Data API supports the downloading of data hosted in the ImmPort Shared Data Warehouse. Endpoints that download Study and Subject level data require Authorization to use these endpoints. Registration to use ImmPort Shared Data is free, visit [ImmPort](https://immport.org) to explore the types of data available for download. Click on this [Link](https://immport-user-admin.niaid.nih.gov:8443/registrationuser/registration) to register.  ## Additional Help For more details on the endpoints visit the [API Documentation Site](https://docs.immport.org/apidocumentation/) for more information. In addition, How-To tutorials on using the endpoints and examples of exploring the data are available [here](https://tutorials.immport.org)  ## Note The Swagger UI can be used to try out endpoints but the Browser can freeze when the endpoint returns large result sets. Either try to add filters to reduce the amount of data returned or test the endpoints with shell scripts using curl or wget.  ## Controllers   | Controller | Description | Authorization | | ---------- | ----------- | ------------- | | Study Search  | Endpoints to support text and facted search of Study and Subject Metadata | No | | Study Data  | These endpoints support the retrieval of study data for a single study including subject, experiment, etc | Yes |         | Study Result | Endpoints to download study, experiment, assay results | Yes |         | Study File Manifest  | These endpoints support retrieving a manifest of all files associated with a given study | Yes | | Download Study Files  | These endpoints support the download of study package files including release files, study files, protocol files and result files using GA4GH DRS ID's. Use the manifest endpoint to retrieve DRS ID for each file | Yes | | Lookup or Controlled Vocabulary | Endpoints to download controlled vocabulary information | No | 

    The version of the OpenAPI document: v1
    Contact: ImmPort_Helpdesk@immport.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immport_client.models.lk_lab_test_panel_name import LkLabTestPanelName

class TestLkLabTestPanelName(unittest.TestCase):
    """LkLabTestPanelName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LkLabTestPanelName:
        """Test LkLabTestPanelName
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LkLabTestPanelName`
        """
        model = LkLabTestPanelName()
        if include_optional:
            return LkLabTestPanelName(
                name = '',
                description = '',
                link = ''
            )
        else:
            return LkLabTestPanelName(
        )
        """

    def testLkLabTestPanelName(self):
        """Test LkLabTestPanelName"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
