# coding: utf-8

"""
    Shared Data API

    # Overview The Shared Data API supports the downloading of data hosted in the ImmPort Shared Data Warehouse. Endpoints that download Study and Subject level data require Authorization to use these endpoints. Registration to use ImmPort Shared Data is free, visit [ImmPort](https://immport.org) to explore the types of data available for download. Click on this [Link](https://immport-user-admin.niaid.nih.gov:8443/registrationuser/registration) to register.  ## Additional Help For more details on the endpoints visit the [API Documentation Site](https://docs.immport.org/apidocumentation/) for more information. In addition, How-To tutorials on using the endpoints and examples of exploring the data are available [here](https://tutorials.immport.org)  ## Note The Swagger UI can be used to try out endpoints but the Browser can freeze when the endpoint returns large result sets. Either try to add filters to reduce the amount of data returned or test the endpoints with shell scripts using curl or wget.  ## Controllers   | Controller | Description | Authorization | | ---------- | ----------- | ------------- | | Study Search  | Endpoints to support text and facted search of Study and Subject Metadata | No | | Study Data  | These endpoints support the retrieval of study data for a single study including subject, experiment, etc | Yes |         | Study Result | Endpoints to download study, experiment, assay results | Yes |         | Study File Manifest  | These endpoints support retrieving a manifest of all files associated with a given study | Yes | | Download Study Files  | These endpoints support the download of study package files including release files, study files, protocol files and result files using GA4GH DRS ID's. Use the manifest endpoint to retrieve DRS ID for each file | Yes | | Lookup or Controlled Vocabulary | Endpoints to download controlled vocabulary information | No | 

    The version of the OpenAPI document: v1
    Contact: ImmPort_Helpdesk@immport.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immport_client.api.lookup_or_controlled_vocabulary_api import LookupOrControlledVocabularyApi


class TestLookupOrControlledVocabularyApi(unittest.TestCase):
    """LookupOrControlledVocabularyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LookupOrControlledVocabularyApi()

    def tearDown(self) -> None:
        pass

    def test_get_lk_adverse_event_severity(self) -> None:
        """Test case for get_lk_adverse_event_severity

        Retrieve LkAdverseEventSeverity Information
        """
        pass

    def test_get_lk_age_event(self) -> None:
        """Test case for get_lk_age_event

        Retrieve LkAgeEvent Information
        """
        pass

    def test_get_lk_analyte(self) -> None:
        """Test case for get_lk_analyte

        Retrieve LkAnalyte Information
        """
        pass

    def test_get_lk_ancestral_population(self) -> None:
        """Test case for get_lk_ancestral_population

        Retrieve LkAncestralPopulation Information
        """
        pass

    def test_get_lk_cell_population(self) -> None:
        """Test case for get_lk_cell_population

        Retrieve LkCellPopulation Information
        """
        pass

    def test_get_lk_cell_population_marker(self) -> None:
        """Test case for get_lk_cell_population_marker

        Retrieve LkCellPopulationMarker Information
        """
        pass

    def test_get_lk_compound_role(self) -> None:
        """Test case for get_lk_compound_role

        Retrieve LkCompoundRole Information
        """
        pass

    def test_get_lk_criterion_category(self) -> None:
        """Test case for get_lk_criterion_category

        Retrieve LkCriterionCategory Information
        """
        pass

    def test_get_lk_data_completeness(self) -> None:
        """Test case for get_lk_data_completeness

        Retrieve LkDataCompleteness Information
        """
        pass

    def test_get_lk_disease(self) -> None:
        """Test case for get_lk_disease

        Retrieve LkDisease Information
        """
        pass

    def test_get_lk_disease_stage(self) -> None:
        """Test case for get_lk_disease_stage

        Retrieve LkDiseaseStage Information
        """
        pass

    def test_get_lk_ethnicity(self) -> None:
        """Test case for get_lk_ethnicity

        Retrieve LkEthnicity Information
        """
        pass

    def test_get_lk_exp_measurement_tech(self) -> None:
        """Test case for get_lk_exp_measurement_tech

        Retrieve LkExpMeasurementTech Information
        """
        pass

    def test_get_lk_exposure_material(self) -> None:
        """Test case for get_lk_exposure_material

        Retrieve LkExposureMaterial Information
        """
        pass

    def test_get_lk_exposure_process(self) -> None:
        """Test case for get_lk_exposure_process

        Retrieve LkExposureProcess Information
        """
        pass

    def test_get_lk_expsample_result_schema(self) -> None:
        """Test case for get_lk_expsample_result_schema

        Retrieve LkExpsampleResultSchema Information
        """
        pass

    def test_get_lk_file_detail(self) -> None:
        """Test case for get_lk_file_detail

        Retrieve LkFileDetail Information
        """
        pass

    def test_get_lk_gender(self) -> None:
        """Test case for get_lk_gender

        Retrieve LkSex Information
        """
        pass

    def test_get_lk_hmdb(self) -> None:
        """Test case for get_lk_hmdb

        Retrieve LkHmdb Information
        """
        pass

    def test_get_lk_lab_test_name(self) -> None:
        """Test case for get_lk_lab_test_name

        Retrieve LkLabTestName Information
        """
        pass

    def test_get_lk_lab_test_panel_name(self) -> None:
        """Test case for get_lk_lab_test_panel_name

        Retrieve LkLabTestPanelName Information
        """
        pass

    def test_get_lk_locus_name(self) -> None:
        """Test case for get_lk_locus_name

        Retrieve LkLocusName Information
        """
        pass

    def test_get_lk_mass_spectrometry_type(self) -> None:
        """Test case for get_lk_mass_spectrometry_type

        Retrieve LkMassSpectrometryType Information
        """
        pass

    def test_get_lk_organization(self) -> None:
        """Test case for get_lk_organization

        Retrieve LkOrganization Information
        """
        pass

    def test_get_lk_personnel_role(self) -> None:
        """Test case for get_lk_personnel_role

        Retrieve LkPersonnelRole Information
        """
        pass

    def test_get_lk_plate_type(self) -> None:
        """Test case for get_lk_plate_type

        Retrieve LkPlateType Information
        """
        pass

    def test_get_lk_protein_name(self) -> None:
        """Test case for get_lk_protein_name

        Retrieve LkProteinName Information
        """
        pass

    def test_get_lk_protocol_type(self) -> None:
        """Test case for get_lk_protocol_type

        Retrieve LkProtocolType Information
        """
        pass

    def test_get_lk_public_repository(self) -> None:
        """Test case for get_lk_public_repository

        Retrieve LkPublicRepository Information
        """
        pass

    def test_get_lk_race(self) -> None:
        """Test case for get_lk_race

        Retrieve LkRace Information
        """
        pass

    def test_get_lk_reagent_type(self) -> None:
        """Test case for get_lk_reagent_type

        Retrieve LkReagentType Information
        """
        pass

    def test_get_lk_research_focus(self) -> None:
        """Test case for get_lk_research_focus

        Retrieve LkResearchFocus Information
        """
        pass

    def test_get_lk_sample_type(self) -> None:
        """Test case for get_lk_sample_type

        Retrieve LkSampleType Information
        """
        pass

    def test_get_lk_source_type(self) -> None:
        """Test case for get_lk_source_type

        Retrieve LkSourceType Information
        """
        pass

    def test_get_lk_species(self) -> None:
        """Test case for get_lk_species

        Retrieve LkSpecies Information
        """
        pass

    def test_get_lk_study_file_type(self) -> None:
        """Test case for get_lk_study_file_type

        Retrieve LkStudyFileType Information
        """
        pass

    def test_get_lk_study_panel(self) -> None:
        """Test case for get_lk_study_panel

        Retrieve LkStudyPanel Information
        """
        pass

    def test_get_lk_subject_location(self) -> None:
        """Test case for get_lk_subject_location

        Retrieve LkSubjectLocation Information
        """
        pass

    def test_get_lk_t0_event(self) -> None:
        """Test case for get_lk_t0_event

        Retrieve LkT0Event Information
        """
        pass

    def test_get_lk_time_unit(self) -> None:
        """Test case for get_lk_time_unit

        Retrieve LkTimeUnit Information
        """
        pass

    def test_get_lk_transcript_type(self) -> None:
        """Test case for get_lk_transcript_type

        Retrieve LkTranscriptType Information
        """
        pass

    def test_get_lk_unit_of_measure(self) -> None:
        """Test case for get_lk_unit_of_measure

        Retrieve LkUnitOfMeasure Information
        """
        pass

    def test_get_lk_user_role_type(self) -> None:
        """Test case for get_lk_user_role_type

        Retrieve LkUserRoleType Information
        """
        pass

    def test_get_lk_virus_strain(self) -> None:
        """Test case for get_lk_virus_strain

        Retrieve LkVirusStrain Information
        """
        pass

    def test_get_lk_visibility_category(self) -> None:
        """Test case for get_lk_visibility_category

        Retrieve LkVisibilityCategory Information
        """
        pass


if __name__ == '__main__':
    unittest.main()
