# coding: utf-8

"""
    Shared Data API

    # Overview The Shared Data API supports the downloading of data hosted in the ImmPort Shared Data Warehouse. Endpoints that download Study and Subject level data require Authorization to use these endpoints. Registration to use ImmPort Shared Data is free, visit [ImmPort](https://immport.org) to explore the types of data available for download. Click on this [Link](https://immport-user-admin.niaid.nih.gov:8443/registrationuser/registration) to register.  ## Additional Help For more details on the endpoints visit the [API Documentation Site](https://docs.immport.org/apidocumentation/) for more information. In addition, How-To tutorials on using the endpoints and examples of exploring the data are available [here](https://tutorials.immport.org)  ## Note The Swagger UI can be used to try out endpoints but the Browser can freeze when the endpoint returns large result sets. Either try to add filters to reduce the amount of data returned or test the endpoints with shell scripts using curl or wget.  ## Controllers   | Controller | Description | Authorization | | ---------- | ----------- | ------------- | | Study Search  | Endpoints to support text and facted search of Study and Subject Metadata | No | | Study Data  | These endpoints support the retrieval of study data for a single study including subject, experiment, etc | Yes |         | Study Result | Endpoints to download study, experiment, assay results | Yes |         | Study File Manifest  | These endpoints support retrieving a manifest of all files associated with a given study | Yes | | Download Study Files  | These endpoints support the download of study package files including release files, study files, protocol files and result files using GA4GH DRS ID's. Use the manifest endpoint to retrieve DRS ID for each file | Yes | | Lookup or Controlled Vocabulary | Endpoints to download controlled vocabulary information | No | 

    The version of the OpenAPI document: v1
    Contact: ImmPort_Helpdesk@immport.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immport_client.api.study_data_api import StudyDataApi


class TestStudyDataApi(unittest.TestCase):
    """StudyDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StudyDataApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_file_details_api(self) -> None:
        """Test case for get_all_file_details_api

        Retrieve All File Path Information
        """
        pass

    def test_get_protocol_file_details_api(self) -> None:
        """Test case for get_protocol_file_details_api

        Retrieve Protocol File Path Information
        """
        pass

    def test_get_restricted_study_accessions(self) -> None:
        """Test case for get_restricted_study_accessions

        """
        pass

    def test_get_result_file_details_api(self) -> None:
        """Test case for get_result_file_details_api

        Retrieve Result File Path Information
        """
        pass

    def test_get_study(self) -> None:
        """Test case for get_study

        Retrieve Basic Study Information
        """
        pass

    def test_get_study_adverse_event_api(self) -> None:
        """Test case for get_study_adverse_event_api

        Retrieve Study Adverse Event Information
        """
        pass

    def test_get_study_arm_api(self) -> None:
        """Test case for get_study_arm_api

        Retrieve Study Arm Information
        """
        pass

    def test_get_study_condition_or_disease(self) -> None:
        """Test case for get_study_condition_or_disease

        Retrieve Study ConditionOrDisease
        """
        pass

    def test_get_study_contract_program(self) -> None:
        """Test case for get_study_contract_program

        Retrieve Study Contract and Program Information
        """
        pass

    def test_get_study_experiment_api(self) -> None:
        """Test case for get_study_experiment_api

        Retrieve Study Experiments
        """
        pass

    def test_get_study_file_api(self) -> None:
        """Test case for get_study_file_api

        Retrieve Study File Information
        """
        pass

    def test_get_study_file_details_api(self) -> None:
        """Test case for get_study_file_details_api

        Retrieve Study File Path Information
        """
        pass

    def test_get_study_immune_exposure_api(self) -> None:
        """Test case for get_study_immune_exposure_api

        Retrieve Study Subject Immune Exposure Information
        """
        pass

    def test_get_study_inclusion_exclusion_api(self) -> None:
        """Test case for get_study_inclusion_exclusion_api

        Retrieve Study Inclusion/Exclusion critera
        """
        pass

    def test_get_study_intervention_api(self) -> None:
        """Test case for get_study_intervention_api

        Retrieve Study Subject Intervention Information
        """
        pass

    def test_get_study_link(self) -> None:
        """Test case for get_study_link

        Retrieve Study Links
        """
        pass

    def test_get_study_personnel(self) -> None:
        """Test case for get_study_personnel

        Retrieve Study Personnel Information
        """
        pass

    def test_get_study_planned_visit(self) -> None:
        """Test case for get_study_planned_visit

        Retrieve Planned Visit Information
        """
        pass

    def test_get_study_protocol(self) -> None:
        """Test case for get_study_protocol

        Retrieve Protocol Information
        """
        pass

    def test_get_study_pubmed(self) -> None:
        """Test case for get_study_pubmed

        Retrieve Pubmed Information
        """
        pass

    def test_get_study_subject_assessment_api(self) -> None:
        """Test case for get_study_subject_assessment_api

        Retrieve Study Subject Assessments
        """
        pass

    def test_get_study_subject_bio_sample_api(self) -> None:
        """Test case for get_study_subject_bio_sample_api

        Retrieve Study Subject BioSample Information
        """
        pass

    def test_get_study_subject_demographic_api(self) -> None:
        """Test case for get_study_subject_demographic_api

        Retrieve Study Subject Demographics
        """
        pass

    def test_get_study_subject_exp_sample_api(self) -> None:
        """Test case for get_study_subject_exp_sample_api

        Retrieve Study Subject ExpSample Information
        """
        pass

    def test_get_study_subject_lab_test_api(self) -> None:
        """Test case for get_study_subject_lab_test_api

        Retrieve Study Subject Lab Tests
        """
        pass

    def test_get_study_summary(self) -> None:
        """Test case for get_study_summary

        """
        pass


if __name__ == '__main__':
    unittest.main()
