"""
    Shared Data API

    # Overview The Shared Data API supports the downloading of data hosted in the ImmPort Shared Data Warehouse. Endpoints that download Study and Subject level data require Authorization to use these endpoints. Registration to use ImmPort Shared Data is free, visit [ImmPort](https://immport.org) to explore the types of data available for download. Click on this [Link](https://immport-user-admin.niaid.nih.gov:8443/registrationuser/registration) to register.  ## Additional Help For more details on the endpoints visit the [API Documentation Site](https://docs.immport.org/apidocumentation/) for more information. In addition, How-To tutorials on using the endpoints and examples of exploring the data are available [here](https://tutorials.immport.org)  ## Note The Swagger UI can be used to try out endpoints but the Browser can freeze when the endpoint returns large result sets. Either try to add filters to reduce the amount of data returned or test the endpoints with shell scripts using curl or wget.  ## Controllers   | Controller | Description | Authorization | | ---------- | ----------- | ------------- | | Study Search  | Endpoints to support text and facted search of Study and Subject Metadata | No | | Study Data  | These endpoints support the retrieval of study data for a single study including subject, experiment, etc | Yes |         | Study Result | Endpoints to download study, experiment, assay results | Yes |         | Study File Manifest  | These endpoints support retrieving a manifest of all files associated with a given study | Yes | | Download Study Files  | These endpoints support the download of study package files including release files, study files, protocol files and result files using GA4GH DRS ID's. Use the manifest endpoint to retrieve DRS ID for each file | Yes | | Lookup or Controlled Vocabulary | Endpoints to download controlled vocabulary information | No | 

    The version of the OpenAPI document: v1
    Contact: ImmPort_Helpdesk@immport.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "immport-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Shared Data API",
    author="ImmPort",
    author_email="ImmPort_Helpdesk@immport.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Shared Data API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    # Overview The Shared Data API supports the downloading of data hosted in the ImmPort Shared Data Warehouse. Endpoints that download Study and Subject level data require Authorization to use these endpoints. Registration to use ImmPort Shared Data is free, visit [ImmPort](https://immport.org) to explore the types of data available for download. Click on this [Link](https://immport-user-admin.niaid.nih.gov:8443/registrationuser/registration) to register.  ## Additional Help For more details on the endpoints visit the [API Documentation Site](https://docs.immport.org/apidocumentation/) for more information. In addition, How-To tutorials on using the endpoints and examples of exploring the data are available [here](https://tutorials.immport.org)  ## Note The Swagger UI can be used to try out endpoints but the Browser can freeze when the endpoint returns large result sets. Either try to add filters to reduce the amount of data returned or test the endpoints with shell scripts using curl or wget.  ## Controllers   | Controller | Description | Authorization | | ---------- | ----------- | ------------- | | Study Search  | Endpoints to support text and facted search of Study and Subject Metadata | No | | Study Data  | These endpoints support the retrieval of study data for a single study including subject, experiment, etc | Yes |         | Study Result | Endpoints to download study, experiment, assay results | Yes |         | Study File Manifest  | These endpoints support retrieving a manifest of all files associated with a given study | Yes | | Download Study Files  | These endpoints support the download of study package files including release files, study files, protocol files and result files using GA4GH DRS ID&#39;s. Use the manifest endpoint to retrieve DRS ID for each file | Yes | | Lookup or Controlled Vocabulary | Endpoints to download controlled vocabulary information | No | 
    """,  # noqa: E501
    package_data={"immport_client": ["py.typed"]},
)
