# coding: utf-8

# flake8: noqa
"""
    Shared Data API

    # Overview The Shared Data API supports the downloading of data hosted in the ImmPort Shared Data Warehouse. Endpoints that download Study and Subject level data require Authorization to use these endpoints. Registration to use ImmPort Shared Data is free, visit [ImmPort](https://immport.org) to explore the types of data available for download. Click on this [Link](https://immport-user-admin.niaid.nih.gov:8443/registrationuser/registration) to register.  ## Additional Help For more details on the endpoints visit the [API Documentation Site](https://docs.immport.org/apidocumentation/) for more information. In addition, How-To tutorials on using the endpoints and examples of exploring the data are available [here](https://tutorials.immport.org)  ## Note The Swagger UI can be used to try out endpoints but the Browser can freeze when the endpoint returns large result sets. Either try to add filters to reduce the amount of data returned or test the endpoints with shell scripts using curl or wget.  ## Controllers   | Controller | Description | Authorization | | ---------- | ----------- | ------------- | | Study Search  | Endpoints to support text and facted search of Study and Subject Metadata | No | | Study Data  | These endpoints support the retrieval of study data for a single study including subject, experiment, etc | Yes |         | Study Result | Endpoints to download study, experiment, assay results | Yes |         | Study File Manifest  | These endpoints support retrieving a manifest of all files associated with a given study | Yes | | Download Study Files  | These endpoints support the download of study package files including release files, study files, protocol files and result files using GA4GH DRS ID's. Use the manifest endpoint to retrieve DRS ID for each file | Yes | | Lookup or Controlled Vocabulary | Endpoints to download controlled vocabulary information | No | 

    The version of the OpenAPI document: v1
    Contact: ImmPort_Helpdesk@immport.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from immport_client.models.file_details import FileDetails
from immport_client.models.filter_criteria_fields import FilterCriteriaFields
from immport_client.models.lk_adverse_event_severity import LkAdverseEventSeverity
from immport_client.models.lk_age_event import LkAgeEvent
from immport_client.models.lk_analyte import LkAnalyte
from immport_client.models.lk_ancestral_population import LkAncestralPopulation
from immport_client.models.lk_cell_population import LkCellPopulation
from immport_client.models.lk_cell_population_marker import LkCellPopulationMarker
from immport_client.models.lk_compound_role import LkCompoundRole
from immport_client.models.lk_criterion_category import LkCriterionCategory
from immport_client.models.lk_data_completeness import LkDataCompleteness
from immport_client.models.lk_disease import LkDisease
from immport_client.models.lk_disease_stage import LkDiseaseStage
from immport_client.models.lk_ethnicity import LkEthnicity
from immport_client.models.lk_exp_measurement_tech import LkExpMeasurementTech
from immport_client.models.lk_exposure_material import LkExposureMaterial
from immport_client.models.lk_exposure_process import LkExposureProcess
from immport_client.models.lk_expsample_result_schema import LkExpsampleResultSchema
from immport_client.models.lk_file_detail import LkFileDetail
from immport_client.models.lk_gender import LkGender
from immport_client.models.lk_hmdb import LkHmdb
from immport_client.models.lk_lab_test_name import LkLabTestName
from immport_client.models.lk_lab_test_panel_name import LkLabTestPanelName
from immport_client.models.lk_locus_name import LkLocusName
from immport_client.models.lk_mass_spectrometry_type import LkMassSpectrometryType
from immport_client.models.lk_organization import LkOrganization
from immport_client.models.lk_personnel_role import LkPersonnelRole
from immport_client.models.lk_plate_type import LkPlateType
from immport_client.models.lk_protein_name import LkProteinName
from immport_client.models.lk_protocol_type import LkProtocolType
from immport_client.models.lk_public_repository import LkPublicRepository
from immport_client.models.lk_race import LkRace
from immport_client.models.lk_reagent_type import LkReagentType
from immport_client.models.lk_research_focus import LkResearchFocus
from immport_client.models.lk_sample_type import LkSampleType
from immport_client.models.lk_source_type import LkSourceType
from immport_client.models.lk_species import LkSpecies
from immport_client.models.lk_study_file_type import LkStudyFileType
from immport_client.models.lk_study_panel import LkStudyPanel
from immport_client.models.lk_subject_location import LkSubjectLocation
from immport_client.models.lk_t0_event import LkT0Event
from immport_client.models.lk_time_unit import LkTimeUnit
from immport_client.models.lk_transcript_type import LkTranscriptType
from immport_client.models.lk_unit_of_measure import LkUnitOfMeasure
from immport_client.models.lk_user_role_type import LkUserRoleType
from immport_client.models.lk_virus_strain import LkVirusStrain
from immport_client.models.lk_visibility_category import LkVisibilityCategory
from immport_client.models.mass_spectrometry_result import MassSpectrometryResult
from immport_client.models.result_file_path import ResultFilePath
from immport_client.models.study_adverse_event_api import StudyAdverseEventApi
from immport_client.models.study_api import StudyApi
from immport_client.models.study_arm_api import StudyArmApi
from immport_client.models.study_condition_or_disease_api import StudyConditionOrDiseaseApi
from immport_client.models.study_contract_program_api import StudyContractProgramApi
from immport_client.models.study_experiment_api import StudyExperimentApi
from immport_client.models.study_file_api import StudyFileApi
from immport_client.models.study_file_details_api import StudyFileDetailsApi
from immport_client.models.study_inclusion_exclusion_api import StudyInclusionExclusionApi
from immport_client.models.study_link import StudyLink
from immport_client.models.study_link_api import StudyLinkApi
from immport_client.models.study_personnel import StudyPersonnel
from immport_client.models.study_personnel_api import StudyPersonnelApi
from immport_client.models.study_planned_visit_api import StudyPlannedVisitApi
from immport_client.models.study_protocol_api import StudyProtocolApi
from immport_client.models.study_pubmed import StudyPubmed
from immport_client.models.study_pubmed_api import StudyPubmedApi
from immport_client.models.study_pubmed_id import StudyPubmedId
from immport_client.models.study_subject_assessments_api import StudySubjectAssessmentsApi
from immport_client.models.study_subject_bio_sample_api import StudySubjectBioSampleApi
from immport_client.models.study_subject_demographics_api import StudySubjectDemographicsApi
from immport_client.models.study_subject_exp_sample_api import StudySubjectExpSampleApi
from immport_client.models.study_subject_immune_exposure_api import StudySubjectImmuneExposureApi
from immport_client.models.study_subject_intervention_api import StudySubjectInterventionApi
from immport_client.models.study_subject_lab_tests_api import StudySubjectLabTestsApi
from immport_client.models.study_summary import StudySummary
from immport_client.models.v_elisa_result import VElisaResult
from immport_client.models.v_elispot_result import VElispotResult
from immport_client.models.v_fcs_analyzed_result import VFcsAnalyzedResult
from immport_client.models.v_hai_result import VHaiResult
from immport_client.models.v_hla_typing_result import VHlaTypingResult
from immport_client.models.v_kir_typing_result import VKirTypingResult
from immport_client.models.v_mbaa_result import VMbaaResult
from immport_client.models.v_neut_ab_titer_result import VNeutAbTiterResult
from immport_client.models.v_pcr_result import VPcrResult
from immport_client.models.v_result_file_path import VResultFilePath

