# coding: utf-8

"""
    Shared Data API

    # Overview The Shared Data API supports the downloading of data hosted in the ImmPort Shared Data Warehouse. Endpoints that download Study and Subject level data require Authorization to use these endpoints. Registration to use ImmPort Shared Data is free, visit [ImmPort](https://immport.org) to explore the types of data available for download. Click on this [Link](https://immport-user-admin.niaid.nih.gov:8443/registrationuser/registration) to register.  ## Additional Help For more details on the endpoints visit the [API Documentation Site](https://docs.immport.org/apidocumentation/) for more information. In addition, How-To tutorials on using the endpoints and examples of exploring the data are available [here](https://tutorials.immport.org)  ## Note The Swagger UI can be used to try out endpoints but the Browser can freeze when the endpoint returns large result sets. Either try to add filters to reduce the amount of data returned or test the endpoints with shell scripts using curl or wget.  ## Controllers   | Controller | Description | Authorization | | ---------- | ----------- | ------------- | | Study Search  | Endpoints to support text and facted search of Study and Subject Metadata | No | | Study Data  | These endpoints support the retrieval of study data for a single study including subject, experiment, etc | Yes |         | Study Result | Endpoints to download study, experiment, assay results | Yes |         | Study File Manifest  | These endpoints support retrieving a manifest of all files associated with a given study | Yes | | Download Study Files  | These endpoints support the download of study package files including release files, study files, protocol files and result files using GA4GH DRS ID's. Use the manifest endpoint to retrieve DRS ID for each file | Yes | | Lookup or Controlled Vocabulary | Endpoints to download controlled vocabulary information | No | 

    The version of the OpenAPI document: v1
    Contact: ImmPort_Helpdesk@immport.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FileDetails(BaseModel):
    """
    FileDetails
    """ # noqa: E501
    file_details_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="fileDetailsId")
    reported_md5: Optional[StrictStr] = Field(default=None, alias="reportedMD5")
    generated_md5: Optional[StrictStr] = Field(default=None, alias="generatedMD5")
    study_accession: Optional[StrictStr] = Field(default=None, alias="studyAccession")
    filesize_bytes: Optional[StrictInt] = Field(default=None, alias="filesizeBytes")
    file_type: Optional[StrictStr] = Field(default=None, alias="fileType")
    file_accession: Optional[StrictStr] = Field(default=None, alias="fileAccession")
    file_name: Optional[StrictStr] = Field(default=None, alias="fileName")
    path: Optional[StrictStr] = None
    date_file_updated: Optional[datetime] = Field(default=None, alias="dateFileUpdated")
    file_uuid: Optional[StrictStr] = Field(default=None, alias="fileUUID")
    drs_object_created: Optional[StrictStr] = Field(default=None, alias="drsObjectCreated")
    workspace_id: Optional[StrictInt] = Field(default=None, alias="workspaceId")
    aigenerated_keywords: Optional[StrictStr] = Field(default=None, alias="aigeneratedKeywords")
    aigenerated_summary: Optional[StrictStr] = Field(default=None, alias="aigeneratedSummary")
    __properties: ClassVar[List[str]] = ["fileDetailsId", "reportedMD5", "generatedMD5", "studyAccession", "filesizeBytes", "fileType", "fileAccession", "fileName", "path", "dateFileUpdated", "fileUUID", "drsObjectCreated", "workspaceId", "aigeneratedKeywords", "aigeneratedSummary"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fileDetailsId": obj.get("fileDetailsId"),
            "reportedMD5": obj.get("reportedMD5"),
            "generatedMD5": obj.get("generatedMD5"),
            "studyAccession": obj.get("studyAccession"),
            "filesizeBytes": obj.get("filesizeBytes"),
            "fileType": obj.get("fileType"),
            "fileAccession": obj.get("fileAccession"),
            "fileName": obj.get("fileName"),
            "path": obj.get("path"),
            "dateFileUpdated": obj.get("dateFileUpdated"),
            "fileUUID": obj.get("fileUUID"),
            "drsObjectCreated": obj.get("drsObjectCreated"),
            "workspaceId": obj.get("workspaceId"),
            "aigeneratedKeywords": obj.get("aigeneratedKeywords"),
            "aigeneratedSummary": obj.get("aigeneratedSummary")
        })
        return _obj


