# coding: utf-8

"""
    Shared Data API

    # Overview The Shared Data API supports the downloading of data hosted in the ImmPort Shared Data Warehouse. Endpoints that download Study and Subject level data require Authorization to use these endpoints. Registration to use ImmPort Shared Data is free, visit [ImmPort](https://immport.org) to explore the types of data available for download. Click on this [Link](https://immport-user-admin.niaid.nih.gov:8443/registrationuser/registration) to register.  ## Additional Help For more details on the endpoints visit the [API Documentation Site](https://docs.immport.org/apidocumentation/) for more information. In addition, How-To tutorials on using the endpoints and examples of exploring the data are available [here](https://tutorials.immport.org)  ## Note The Swagger UI can be used to try out endpoints but the Browser can freeze when the endpoint returns large result sets. Either try to add filters to reduce the amount of data returned or test the endpoints with shell scripts using curl or wget.  ## Controllers   | Controller | Description | Authorization | | ---------- | ----------- | ------------- | | Study Search  | Endpoints to support text and facted search of Study and Subject Metadata | No | | Study Data  | These endpoints support the retrieval of study data for a single study including subject, experiment, etc | Yes |         | Study Result | Endpoints to download study, experiment, assay results | Yes |         | Study File Manifest  | These endpoints support retrieving a manifest of all files associated with a given study | Yes | | Download Study Files  | These endpoints support the download of study package files including release files, study files, protocol files and result files using GA4GH DRS ID's. Use the manifest endpoint to retrieve DRS ID for each file | Yes | | Lookup or Controlled Vocabulary | Endpoints to download controlled vocabulary information | No | 

    The version of the OpenAPI document: v1
    Contact: ImmPort_Helpdesk@immport.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StudySubjectInterventionApi(BaseModel):
    """
    StudySubjectInterventionApi
    """ # noqa: E501
    study_accession: Optional[StrictStr] = Field(default=None, alias="studyAccession")
    brief_title: Optional[StrictStr] = Field(default=None, alias="briefTitle")
    arm_accession: Optional[StrictStr] = Field(default=None, alias="armAccession")
    arm_name: Optional[StrictStr] = Field(default=None, alias="armName")
    arm_description: Optional[StrictStr] = Field(default=None, alias="armDescription")
    arm_type_reported: Optional[StrictStr] = Field(default=None, alias="armTypeReported")
    arm_type_preferred: Optional[StrictStr] = Field(default=None, alias="armTypePreferred")
    subject_accession: Optional[StrictStr] = Field(default=None, alias="subjectAccession")
    age_event: Optional[StrictStr] = Field(default=None, alias="ageEvent")
    age_event_specify: Optional[StrictStr] = Field(default=None, alias="ageEventSpecify")
    age_unit: Optional[StrictStr] = Field(default=None, alias="ageUnit")
    max_subject_age: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maxSubjectAge")
    min_subject_age: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="minSubjectAge")
    subject_phenotype: Optional[StrictStr] = Field(default=None, alias="subjectPhenotype")
    subject_location: Optional[StrictStr] = Field(default=None, alias="subjectLocation")
    max_subject_age_in_years: Optional[StrictStr] = None
    min_subject_age_in_years: Optional[StrictStr] = None
    ancestral_population: Optional[StrictStr] = None
    subject_description: Optional[StrictStr] = Field(default=None, alias="subjectDescription")
    ethnicity: Optional[StrictStr] = None
    gender: Optional[StrictStr] = None
    race: Optional[StrictStr] = None
    race_specify: Optional[StrictStr] = Field(default=None, alias="raceSpecify")
    species: Optional[StrictStr] = None
    strain: Optional[StrictStr] = None
    strain_characteristics: Optional[StrictStr] = None
    intervention_accession: Optional[StrictStr] = Field(default=None, alias="interventionAccession")
    compound_name_reported: Optional[StrictStr] = Field(default=None, alias="compoundNameReported")
    compound_role: Optional[StrictStr] = Field(default=None, alias="compoundRole")
    dose: Optional[StrictStr] = None
    dose_freq_per_interval: Optional[StrictStr] = Field(default=None, alias="doseFreqPerInterval")
    dose_reported: Optional[StrictStr] = Field(default=None, alias="doseReported")
    dose_units: Optional[StrictStr] = Field(default=None, alias="doseUnits")
    duration: Optional[StrictStr] = None
    duration_unit: Optional[StrictStr] = Field(default=None, alias="durationUnit")
    end_day: Optional[StrictStr] = Field(default=None, alias="endDay")
    end_time: Optional[StrictStr] = Field(default=None, alias="endTime")
    formulation: Optional[StrictStr] = None
    is_ongoing: Optional[StrictStr] = Field(default=None, alias="isOngoing")
    name_preferred: Optional[StrictStr] = Field(default=None, alias="namePreferred")
    name_reported: Optional[StrictStr] = Field(default=None, alias="nameReported")
    reported_indication: Optional[StrictStr] = Field(default=None, alias="reportedIndication")
    route_of_admin_preferred: Optional[StrictStr] = Field(default=None, alias="routeOfAdminPreferred")
    route_of_admin_reported: Optional[StrictStr] = Field(default=None, alias="routeOfAdminReported")
    start_day: Optional[StrictStr] = Field(default=None, alias="startDay")
    start_time: Optional[StrictStr] = Field(default=None, alias="startTime")
    status: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["studyAccession", "briefTitle", "armAccession", "armName", "armDescription", "armTypeReported", "armTypePreferred", "subjectAccession", "ageEvent", "ageEventSpecify", "ageUnit", "maxSubjectAge", "minSubjectAge", "subjectPhenotype", "subjectLocation", "max_subject_age_in_years", "min_subject_age_in_years", "ancestral_population", "subjectDescription", "ethnicity", "gender", "race", "raceSpecify", "species", "strain", "strain_characteristics", "interventionAccession", "compoundNameReported", "compoundRole", "dose", "doseFreqPerInterval", "doseReported", "doseUnits", "duration", "durationUnit", "endDay", "endTime", "formulation", "isOngoing", "namePreferred", "nameReported", "reportedIndication", "routeOfAdminPreferred", "routeOfAdminReported", "startDay", "startTime", "status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StudySubjectInterventionApi from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StudySubjectInterventionApi from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "studyAccession": obj.get("studyAccession"),
            "briefTitle": obj.get("briefTitle"),
            "armAccession": obj.get("armAccession"),
            "armName": obj.get("armName"),
            "armDescription": obj.get("armDescription"),
            "armTypeReported": obj.get("armTypeReported"),
            "armTypePreferred": obj.get("armTypePreferred"),
            "subjectAccession": obj.get("subjectAccession"),
            "ageEvent": obj.get("ageEvent"),
            "ageEventSpecify": obj.get("ageEventSpecify"),
            "ageUnit": obj.get("ageUnit"),
            "maxSubjectAge": obj.get("maxSubjectAge"),
            "minSubjectAge": obj.get("minSubjectAge"),
            "subjectPhenotype": obj.get("subjectPhenotype"),
            "subjectLocation": obj.get("subjectLocation"),
            "max_subject_age_in_years": obj.get("max_subject_age_in_years"),
            "min_subject_age_in_years": obj.get("min_subject_age_in_years"),
            "ancestral_population": obj.get("ancestral_population"),
            "subjectDescription": obj.get("subjectDescription"),
            "ethnicity": obj.get("ethnicity"),
            "gender": obj.get("gender"),
            "race": obj.get("race"),
            "raceSpecify": obj.get("raceSpecify"),
            "species": obj.get("species"),
            "strain": obj.get("strain"),
            "strain_characteristics": obj.get("strain_characteristics"),
            "interventionAccession": obj.get("interventionAccession"),
            "compoundNameReported": obj.get("compoundNameReported"),
            "compoundRole": obj.get("compoundRole"),
            "dose": obj.get("dose"),
            "doseFreqPerInterval": obj.get("doseFreqPerInterval"),
            "doseReported": obj.get("doseReported"),
            "doseUnits": obj.get("doseUnits"),
            "duration": obj.get("duration"),
            "durationUnit": obj.get("durationUnit"),
            "endDay": obj.get("endDay"),
            "endTime": obj.get("endTime"),
            "formulation": obj.get("formulation"),
            "isOngoing": obj.get("isOngoing"),
            "namePreferred": obj.get("namePreferred"),
            "nameReported": obj.get("nameReported"),
            "reportedIndication": obj.get("reportedIndication"),
            "routeOfAdminPreferred": obj.get("routeOfAdminPreferred"),
            "routeOfAdminReported": obj.get("routeOfAdminReported"),
            "startDay": obj.get("startDay"),
            "startTime": obj.get("startTime"),
            "status": obj.get("status")
        })
        return _obj


